---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/release-cli --version
    register: glreleasecli_test_output
  - name: release-cli --version
    debug:
      msg: '{{ glreleasecli_test_output.stdout }}'
